package modelo;
// Generated 11 feb 2025, 17:57:30 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Estilo generated by hbm2java
 */
public class Estilo implements java.io.Serializable {

	private Integer idEstilo;
	private String nomEstilo;
	private Set musicas = new HashSet(0);

	public Estilo() {
	}

	public Estilo(String nomEstilo) {
		this.nomEstilo = nomEstilo;
	}

	public Estilo(String nomEstilo, Set musicas) {
		this.nomEstilo = nomEstilo;
		this.musicas = musicas;
	}

	public Integer getIdEstilo() {
		return this.idEstilo;
	}

	public void setIdEstilo(Integer idEstilo) {
		this.idEstilo = idEstilo;
	}

	public String getNomEstilo() {
		return this.nomEstilo;
	}

	public void setNomEstilo(String nomEstilo) {
		this.nomEstilo = nomEstilo;
	}

	public Set getMusicas() {
		return this.musicas;
	}

	public void setMusicas(Set musicas) {
		this.musicas = musicas;
	}

}
